# Generated by Django 4.0.1 on 2022-02-07 09:40

import datetime
from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('be_fit', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='User_otp',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('otp', models.CharField(max_length=6)),
                ('otp_generate_time', models.DateTimeField(default=datetime.datetime(2022, 2, 7, 9, 40, 18, 381731, tzinfo=utc))),
                ('otp_expiration_time', models.DateTimeField(default=datetime.datetime(2022, 2, 7, 9, 42, 18, 381774, tzinfo=utc))),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.DeleteModel(
            name='Registered_Users',
        ),
    ]
