# Generated by Django 4.0.1 on 2022-02-07 12:20

import datetime
from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('be_fit', '0003_alter_user_otp_otp_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user_otp',
            name='otp',
            field=models.CharField(max_length=6),
        ),
        migrations.AlterField(
            model_name='user_otp',
            name='otp_expiration_time',
            field=models.DateTimeField(default=datetime.datetime(2022, 2, 7, 12, 22, 9, 588884, tzinfo=utc)),
        ),
        migrations.AlterField(
            model_name='user_otp',
            name='otp_generate_time',
            field=models.DateTimeField(default=datetime.datetime(2022, 2, 7, 12, 20, 9, 588843, tzinfo=utc)),
        ),
        migrations.AlterField(
            model_name='user_otp',
            name='user',
            field=models.OneToOneField(null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
    ]
